### ISSUE TITLE
Fix only complete words

### ISSUE THREAD

**Issue by mkonersmann** [wburningham/AutoSpell#10]
This plugin, while very useful most of the times, systematically introduces faults into my texts, because it corrects the ending of words when the end of the word matches a replacement entry.

Specifically, when I write the (German) word `möchte`, it automatically changes it to `möcthe`, because `"hte": "the"` is in default_replacements, and the space character after the word is in `default_triggers`.

IMO the replacement entries should only match for whole words, not for parts of a word. Probably a configuration trigger can be introduced to not change the default behavior.

**Comment by wburningham** [comment]
I no longer maintain this project. I personally now use [Alfred](https://www.alfredapp.com/) snippets (it may be a powerpack feature) or I'd recommend using [aText](https://www.trankynam.com/atext/).
