### ISSUE TITLE
Breaks Indents and return within html for php encoded files

### ISSUE THREAD

**Issue by BlueJ-D** [wburningham/AutoSpell#12]
A restart of sublime caused me to lose indent and line feed functionality on any html and blank lines - php code lines were fine ie between <?php ?>.

I narrowed it down to this plugin / package alone causing the issue. Even with every other package ignored / disabled and this one enabled it killed all ability to indent and newline (within html). Since removing st3 also seems to run smoother, but could be the update of the app.

sublime build version 3176 3.1.1

**Comment by wburningham** [comment]
I no longer maintain this project. I personally now use [Alfred](https://www.alfredapp.com/) snippets (it may be a powerpack feature) or I'd recommend using [aText](https://www.trankynam.com/atext/).
