### ISSUE TITLE
Expand text without having to hit space

### ISSUE THREAD

**Issue by ghost** [wburningham/AutoSpell#14]
I would like to expand << to “ but without having to type a space as a trigger. I.e. when I type the second < it expands. Is this possible?

**Comment by wburningham** [comment]
I no longer maintain this project. I personally now use [Alfred](https://www.alfredapp.com/) snippets (it may be a powerpack feature) or I'd recommend using [aText](https://www.trankynam.com/atext/).

**Comment by ghost** [comment]
Thanks for the recommendations. I still use and enjoy AutoSpell.
