### ISSUE TITLE
Causes Issues with Sublime File Browser Package

### ISSUE THREAD

**Issue by excetara2** [wburningham/AutoSpell#6]
The keybindings are single characters in the sublime File Browser package and these seem to conflight with Autospell. If I use FindKeyConflights many come up as well as the keybindings don't work properly so I have disabled AutoSpell for now. The author had stated it was possible probably to turn AutoSpell off in a read only window as the dired window is.

Is this possible to implement or do you know why the conflict is ocurring?

This is the post in Sublime File Browser:
[https://github.com/aziz/SublimeFileBrowser/issues/108#issuecomment-205679477](https://github.com/aziz/SublimeFileBrowser/issues/108#issuecomment-205679477)

**Comment by wburningham** [comment]
I no longer maintain this project. I personally now use [Alfred](https://www.alfredapp.com/) snippets (it may be a powerpack feature) or I'd recommend using [aText](https://www.trankynam.com/atext/).
